# Generated by Django 6.0.4 on 2026-06-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('password2', models.CharField(max_length=300)),
            ],
        ),
    ]
