# Generated by Django 6.0.4 on 2026-06-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
